apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-schema-registry
  namespace: kafka
  labels:
    app: kafka-schema-registry
spec:
  selector:
    matchLabels:
      app: kafka-schema-registry
  template:
    metadata:
      labels:
        app: kafka-schema-registry
    spec:
      containers:
        - name: kafka-schema-registry
          image: confluentinc/cp-schema-registry:7.2.1
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "PLAINTEXT://lab-kafka-kafka-bootstrap.kafka:9092"
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "kafka-schema-registry"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-schema-registry
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: kafka-schema-registry
  ports:
  - name: schema-registry
    protocol: TCP
    port: 8081
    targetPort: 8081