kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/whitelist-source-range: 127.0.0.1/8,169.254.0.0/16,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
spec:
  rules:
    - host: argocd.cluster.lab
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
