apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
  labels:
    app: kafka-ui
spec:
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:a9c31e6a32c222da2d28896ec2acbccdf7b308c5
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "lab-cluster"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "lab-cluster-kafka-bootstrap.kafka:9092"
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: "lab-cluster-zookeeper-nodes.kafka:2181"
            - name: KAFKA_CLUSTERS_0_KSQLDBSERVER
              value: "kafka-ksqldb.kafka:8088"
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              value: "kafka-schema-registry.kafka:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  selector:
    app: kafka-ui
  ports:
  - name: ui
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop-ui
  namespace: kafka
  labels:
    app: kafdrop-ui
spec:
  selector:
    matchLabels:
      app: kafdrop-ui
  template:
    metadata:
      labels:
        app: kafdrop-ui
    spec:
      containers:
        - name: kafdrop-ui
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERCONNECT
              value: "lab-cluster-kafka-bootstrap.kafka:9092"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
            - name: JVM_OPTS
              value: "-Xms32M -Xmx64M"
            - name: CMD_ARGS
              value: "--schemaregistry.connect=kafka-schema-registry.kafka:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-ui
  namespace: kafka
spec:
  selector:
    app: kafdrop-ui
  ports:
  - name: ui
    protocol: TCP
    port: 9000
    targetPort: 9000