kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "lab-keycloak-db"
  namespace: "default"
  labels:
    team: lab

spec:
  teamId: "lab"
  postgresql:
    version: "14"
  numberOfInstances: 1
  volume:
    size: "10Gi"
  users:
    keycloak: []
  databases:
    keycloak: keycloak
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi