apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  # type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:19.0.1
        args: [
          "start",
          "--db=postgres",
          "--db-password=$(KEYCLOAK_DB_PASSWORD)",
          "--db-username=$(KEYCLOAK_DB_USERNAME)",
          "--db-url=jdbc:postgresql://lab-keycloak-db.default:5432/keycloak",
          "--features=scripts",
          "--health-enabled=true",
          "--metrics-enabled=true",
        ]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_HOSTNAME
          value: "auth.cluster.lab"
        - name: KC_PROXY
          value: "edge"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_FRONTEND_URL
          value: "https://auth.cluster.lab/auth/"
        - name: KEYCLOAK_ADMIN_URL
          value: "https://auth.cluster.lab/auth/realms/master/admin/"
        - name: KEYCLOAK_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak.lab-keycloak-db.credentials.postgresql.acid.zalan.do
              key: password
        - name: KEYCLOAK_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak.lab-keycloak-db.credentials.postgresql.acid.zalan.do
              key: username
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
